### ISSUE TITLE
TypeError: Cannot read property 'ctype' of undefined

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#56]
``` coffee
    at Contract.c.equals (vendor/contracts.js:1061:46)
    at checkOptions (vendor/contracts.js:466:22)
    at Contract.c.equals (vendor/contracts.js:1062:14)
    at c.equals.pCDom (vendor/contracts.js:794:22)
    at Array.every (native)
    at Contract.c.equals (vendor/contracts.js:793:49)
    at Contract.check (vendor/contracts.js:593:18)
    at Object.handler.get (vendor/contracts.js:961:45)
    at Object.Yap.define.angular.module.factory.api.apiCall (app/Prelude.js?_dc=1348410923903:470:90)
  at Object.Yap.define.addContractMethods.apiCall (lib/api/EPG.js?_dc=1348410924047:247:25)
```

**Comment by disnet** [comment]
Does this fix for you? Having trouble reproducing but this might fix it.

**Comment by gregwebs** [comment]
my code base has been changing, so not sure if the contract will get hit the same way anymore. I will re-open if I see this again.
