### ISSUE TITLE
TypeError: Object.getPrototypeOf called on non-object

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#58]
TypeError: Object.getPrototypeOf called on non-object
    at Function.getPrototypeOf (native)
    at Contract.handler (http://local.yap.tv:9292/vendor/contracts.js:1040:24)
    at Contract.check (http://local.yap.tv:9292/vendor/contracts.js:617:21)
    at Object.functionHandler (http://local.yap.tv:9292/vendor/contracts.js:754:39)
    at Object.statechart.addState.states.states.states.enterState (http://local.yap.tv:9292/app/view/MasterEpisodes.js:373:43)

This is triggered by a line that calls `activeShows.set`

``` coffee
activeShows.set :: ([...ShowC], Str?) -> [...ShowC]

ShowC = ?({ 
  name: Str 
  id: Pos
})
```

**Comment by disnet** [comment]
Odd, do you know what is being passed to `activeShows.set` when it fails like this? Normally if you pass a non-object it throws a blame exception before getting to the `getPrototypeOf` call so I'm not sure why this is failing.

**Comment by gregwebs** [comment]
Sorry, should have mentioned that: it was being passed in just `null` as a first argument.

**Comment by disnet** [comment]
Apparently calling getPrototypeOf on `null` isn't allowed. Should throw the correct blame message now.
